apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: configmap-volume
      mountPath: /sudharshan/configfolder
    - name: secret-volume
      mountPath: /sudharshan/secretfolder
  volumes:
  - name: configmap-volume
    configMap:
      name: nginx-configmap
  - name: secret-volume
    secret:
      secretName: nginx-secret
  restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  sample.txt: "Hello Team!"
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
data:
  username: "c3VkaGFyc2hhbgo="
  password: "MTIzNDU2Cg=="