apiVersion: v1
kind: Pod
metadata:
  name: smur-executor
spec:
  runtimeClassName: kata-remote
  containers:
    - name: smur-container
      image: nginx
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: secret-volume
          mountPath: /etc/secret
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
    - name: secret-volume
      secret:
        secretName: nginx-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  example.txt: |
    Hello, world
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
data:
  password: MTIzNDU2
  username: YWRtaW4=
type: Opaque