apiVersion: v1
kind: Pod
metadata:
  name: useradd-nginx
spec:
  runtimeClassName: kata-remote
  containers:
    - name: nginx-container
      image: nginx:latest
      env:
        - name: "ISPRODUCTION"
          value: "false"
      command: ["/bin/sh","-c","env"]
      ports:
        - containerPort: 80
  initContainers:
    - name: useradd-init-container
      image: busybox
      command: ["adduser", "-D", "nginx"]
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
    name: normal-nginx
spec:
    runtimeClassName: kata-remote
    containers:
      - name: env-variable-in-config
        image: nginx:latest
        env:
          - name: "ISPRODUCTION"
            value: "false"
        command: ["/bin/sh","-c","env"]
    restartPolicy: OnFailure